services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
        #environment:
      #WORDPRESS_DB_HOST: mariadb:3306
      #WORDPRESS_DB_USER: ${MYSQL_USER}
      #WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      #WORDPRESS_DB_NAME: ${MYSQL_DB}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - '9000:9000'
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always


volumes:
  mariadb_data:
    name: mariadb_vlm
    driver: local
    driver_opts:
      type: none
      device: /home/njeanbou/data/mariadb_data
      o: bind
  wordpress_data:
    name: wordpress_vlm
    driver: local
    driver_opts:
      type: none
      device: /home/njeanbou/data/wordpress_data
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

