services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/njeanbou/data/wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DB}
    volumes:
      - wordpress_data:/var/www/html
      - /home/njeanbou/data/mariadb_data:/var/lib/mysql
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - '9000:9000'
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env    
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
    name: mariadb_vlm
    driver: local
  wordpress_data:
    name: wordpress_vlm
    driver: local

networks:
  inception:
    name: inception
    driver: bridge

